### ISSUE TITLE
Output?

### ISSUE THREAD

**Issue by KeyC0de** [Atvaark/GzsTool#11]
Running the program `GzsTool.exe S:\Steam\SteamApps\path\wherever\chunk0.dat` it threw all the data in some obscure (hidden!) directory placed inside the root directory of the drive named `VTRoot` that the program ran on. What is that supposed to be? 

I was wondering why would you do this... A sane program would work as simple as this: `program.exe C:\target\file.extension D:\output\directory`. I was searching (for 10 minutes!) to find the output directory after searching for ~5 minutes first on whether such a command I illustrated exists. But apparently that's not very intuitive here. Ok.

Alright. Thanks. Just wanted to mention that for any other stragglers.

**Comment by Atvaark** [comment]
Hey,

are you sure this isn't your antivirus messing with this application?
The output is normally written to the same directory as the source file.

**Comment by KeyC0de** [comment]
Yes, I'm sure I did it again from an admin cmd with antivirus off. Very strange. I'm on Windows 8.1 x64, fulfill all requirements.

**Comment by Atvaark** [comment]
Are you using `Comodo Internet Security`?

https://steamcommunity.com/discussions/forum/1/617328967248066054/

**Comment by KeyC0de** [comment]
Yeah, I actually found out a while ago and I was going to notify you. I installed Comodo last week, because its free and my Kaspersky license ended. It is really bugging me constantly.. I have to get rid of it asap. Sorry for the trouble.
