### ISSUE TITLE
Non-negative number required.

### ISSUE THREAD

**Issue by LordFuse** [Atvaark/GzsTool#13]
Heya, same issue as the last person, although I can attach a file.
I'm using the latest version of your software and windows 10, although I'm pretty sure it's got to do with the file itself. Would appreciate any help.

[assets.zip](https://github.com/Atvaark/GzsTool/files/4049538/assets.zip)

**Comment by Atvaark** [comment]
Hey, which game and version is that file from?

**Comment by LordFuse** [comment]
If you mean version of your tool, then 0.6.0.
The file is from a game launcher called FusionFall Universe.(https://cdn.fusionfalluniverse.com/launcher/ULInstaller.exe) v1.0.5 of that.
It has some a bunch of cool artwork I thought might be neat to get.

**Comment by Atvaark** [comment]
That's a unity and not a fox engine game.

**Comment by LordFuse** [comment]
My bad.
