### ISSUE TITLE
Error in cpk file format version

### ISSUE THREAD

**Issue by Meetrawal** [Atvaark/GzsTool#14]
Hi ,
I am creating patch for pes 2020 mobile , i saw vedio on YouTube and tried
I got successful every tym when i made changes in my patch
Bt after 9/4/2020 update when i load patch obb in my phone ,pes starts download ita own patch 

I created again and again bt every tym pes dwnld it's own patch , so it's mean my patch has error
I noticed that in my patch (created) dt.cpk files has different file format version that og file format.
So how to resolve this error

**Comment by Atvaark** [comment]
I cannot help you with that game.

You could try asking a group for that game for help or someone that knows about these .cpk file.
