### ISSUE TITLE
*other games*

### ISSUE THREAD

**Issue by EternalShackles** [Atvaark/GzsTool#16]
Hello, I guess you are way out of scene by now but would it somehow be possible adding support for fpk files in fate Unlimited Codes and bleach hts 7 (both are using same structure). As of now I failed to find any tool that can properly unpack and repack them. Ty...

**Comment by ehsanmousavizare** [comment]
I want to extract SBP file from God of War 2018 PC  but its not working and xml file and folder is empty

**Comment by Atvaark** [comment]
God of War isn't using Fox Engine as far as I know.
This or other similar tools won't work with these files.

Have you checked if there are any specific scripts or tools for your game? 
https://fileforums.com/showthread.php?p=495954

**Comment by ehsanmousavizare** [comment]
Appreciate it
I check the forum but the download link of SBP Tool for GOW not working
Do you have that tool?

**Comment by Atvaark** [comment]
No
