### ISSUE TITLE
Crashing upon compiling

### ISSUE THREAD

**Issue by PonyTerrance** [Atvaark/GzsTool#2]
My problem is as follows. I believe I have followed the commands correctly, but I get this:

http://puu.sh/oKF3s/2219c1a5be.png

The program crashes and doesn't compile the files into a new .dat

**Comment by Atvaark** [comment]
Please attach the xml file and tell me which version of GzsTool you are using.

**Comment by PonyTerrance** [comment]
Latest as of 09/May/2016, v0.5.2.2

[data1.dat.xml..zip](https://github.com/Atvaark/GzsTool/files/254156/data1.dat.xml.zip)

**Comment by Atvaark** [comment]
Use v0.2 for the Ground Zeroes archives.

**Comment by PonyTerrance** [comment]
Its for TPP

**Comment by PonyTerrance** [comment]
Tried all releases. Still crashing, when compiling or uncompiling. Please advise

**Comment by Atvaark** [comment]
Could you try passing an absolute path to the .dat.xml file into the tool?

**Comment by PonyTerrance** [comment]
C:\Users\Terry\Documents\mgsv reward\data1.dat.xml

**Comment by Atvaark** [comment]
Same issue?
I checked earlier today and I could read the .xml file you attached without issues.

**Comment by PonyTerrance** [comment]
Yeah, same issue. Just tried again. No luck

**Comment by Atvaark** [comment]
Could you check if you can unpack and repack these 2 test .dat files?
- test1 contains a single file
- test2 contains no files

[test.zip](https://github.com/Atvaark/GzsTool/files/263689/test.zip)

**Comment by PonyTerrance** [comment]
I can pack and unpack both without error

**Comment by Atvaark** [comment]
I can't reproduce your issue on my systems (Windows 7 and a Windows 10 VM).

This batch script worked without any issues (see the attached log file)

```
dir /S /B "C:\GzsToolTest\master"
"C:\GzsToolTest\GzsTool v0.5.2.2\GzsTool.exe" "C:\GzsToolTest\master\data1.dat"
dir /S /B "C:\GzsToolTest\master\data1_dat"
del "C:\GzsToolTest\master\data1.dat"
"C:\GzsToolTest\GzsTool v0.5.2.2\GzsTool.exe" "C:\GzsToolTest\master\data1.dat.xml"
del "C:\GzsToolTest\master\data1.dat.xml"
rd /S /Q "C:\GzsToolTest\master\data1_dat"
dir /S /B "C:\GzsToolTest\master"
```

[run.txt](https://github.com/Atvaark/GzsTool/files/264580/run.txt)

**Comment by Atvaark** [comment]
Closed due to inactivity.
