### ISSUE TITLE
Unpacking a dat in the same directory as the tool create the output folder at the root of the drive

### ISSUE THREAD

**Issue by gabfv** [Atvaark/GzsTool#4]
Hi,
I've found a relatively minor bug.

I copied the tool in my installation folder for MGSV:TPP, under master/:
`D:\Steam\steamapps\common\MGS_TPP\master`

I opened a cmd prompt in that folder (_using shift+right click, open command window here_).
I tried the unpack the data1.dat file by using this command:
`GzsTool.exe data1.dat`
It looked like this in the cmd prompt:
`D:\Steam\steamapps\common\MGS_TPP\master>GzsTool.exe data1.dat`

However, it unpacked the files in a folder directly at the root of the drive, which was:
`D:\data1_dat\`

I believe it should unpack the files directly in the same folder, like this:
`D:\Steam\steamapps\common\MGS_TPP\master\data1_dat`

I also found a workaround, somehow, moving the current working directly to the parent folder so the command is executed like that:
`D:\Steam\steamapps\common\MGS_TPP>master\GzsTool.exe master\data1.dat`
It unpacked the files in what should be the correct folder:
`D:\Steam\steamapps\common\MGS_TPP\master\data1_dat`

**Comment by Atvaark** [comment]
Thanks for the report.

Turns out I fixed this in my local repository about a year ago and didn't push it to Github.

I pushed the commit and a tag just now and a fixed release will be available soon. Please check if it is fixed. (I can't test it right now as I don't have MGSV installed.)

**Comment by gabfv** [comment]
Thanks, it actually works correctly now!
