### ISSUE TITLE
Unpacking error

### ISSUE THREAD

**Issue by PatrickLeoMaxwell** [Atvaark/GzsTool#6]
Hey, I have a problem when trying to unpack fpk file. The Gzs Tool crashes and gives this messages.
I've been trying to unpack the face.fpk file from PES 2018 dat but nothing works for me. Any solution what may cause this problem?

Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at GzsTool.Core.Fpk.FpkFile.Read(Stream input)
   at GzsTool.Program.ReadArchive[T](String path)
   at GzsTool.Program.Main(String[] args)

Unhandled Exception: System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: value
   at System.IO.FileStream.set_Position(Int64 value)
   at GzsTool.Core.Fpk.FpkString.Read(Stream input)
   at GzsTool.Core.Fpk.FpkEntry.Read(Stream input)
   at GzsTool.Core.Fpk.FpkFile.Read(Stream input)
   at GzsTool.Program.ReadArchive[T](String path)
   at GzsTool.Program.Main(String[] args)

**Comment by Atvaark** [comment]
The format could be completely different from the fox engine 2015 format.
Do any other files from PES even unpack with GzsTool?
Are these PC or console files?

**Comment by PatrickLeoMaxwell** [comment]
https://www.youtube.com/watch?v=HC8MA6lqY-0

There's a link on video where the guy uses the same fpk files with your tool and it works for him. And I'm also using PC files not the console ones. I was lucky to unpack just some random files. But they're the ones i don't want, I need to unpack the other so.

**Comment by Atvaark** [comment]
Are you using the latest version of GzsTool?
I can't really help you without access to the files that don't work for you.

**Comment by Isakooov** [comment]
Hello, Atvaark! Congrats first of all on this wonderful tool!

I am the author of that PES 2018 tutorial video PatrickLeoMaxwell posted earlier.

Interestingly the tool works for some files and crashes on others. I'm uploading three fpk folders, one which unpacks without problem and two that return different errors.
[PES 2018 Structure.zip](https://github.com/Atvaark/GzsTool/files/1383295/PES.2018.Structure.zip)

PES 2018 modders use GzsTool v0.5.2, I believe it is the latest version. Cheers!

**Comment by Atvaark** [comment]
Only one of the files is a valid fpk file. If you open them in a text editor it has to start with "foxfpk" or "foxfpkd".
Are you sure that the tool you are using to create the fpk files is working correctly?

**Comment by Isakooov** [comment]
I'm not creating anything, they are extracted from .cpk file (using CRI Packed File Maker v1.36).

I just checked in text editor the other two invalid fpk files, obviously they are encrypted. That means your tool works just fine. Thanks for the hint and thanks again for this tool! 🥇

**Comment by Isakooov** [comment]
Ah, it's me again. Sorry for bothering you once more, but I'm stuck on another issue. Any idea on **.fkpd** files purpose that come along with .fkp ones? Cheers!

**Comment by Atvaark** [comment]
They're pretty much the same files as .fpk ones.

**Comment by rokoni99** [comment]
(PatrickLeoMaxwell) 

HI bro, I have Exactly same problem 
Please bro have you fixed your problem yet??? I mean the error message??
Because I can't find Solution for it

**Comment by rokoni99** [comment]
(PatrickLeoMaxwell) 

HI bro, I have Exactly same problem 
Please bro have you fixed your problem yet??? I mean the error message??
Because I can't find Solution for it
